# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Memory_Allocator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1270, 944)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/memory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     \n"
"    background: none;\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"        background-color: rgb(170, 0, 0);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background-color: rgb(170, 0, 0);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"          background-color: rgb(170, 0, 0);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"       background: none;\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"         background-color: rgb(170, 0, 0);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"       background-color: rgb(170, 0, 0);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"         background-color: rgb(170, 0, 0);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"   \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"#centralwidget{\n"
"    border-image: url(:/newPrefix/neven_qrc/فهرس.jpg);\n"
"}\n"
"\n"
"#toolBox_2{\n"
"    border-image: url(:/newPrefix/neven_qrc/فهرس.jpg);\n"
"}\n"
"#scrollAreaWidgetContents{border-image: url(:/newPrefix/neven_qrc/فهرس.jpg);\n"
"}\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: rgb(170, 0, 0);\n"
"}\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border-color: rgb(170, 0, 0);\n"
"}\n"
"QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #b1b1b1;\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTreeView, QListView\n"
"{\n"
"    background-color: silver;\n"
"    margin-left: 5px;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #808080;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    /*border: 1px solid darkgray;*/\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"\n"
"    background-color: rgb(0, 85, 255);\n"
"}\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/dark_orange/img/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox\n"
"{\n"
"    border: 1px solid darkgray;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"    border: 1px solid darkgray;\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 1px solid darkgray;\n"
"}\n"
"\n"
"\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"  \n"
"\n"
" background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgb(208, 0, 0), stop: 0.5 rgb(170, 0, 0));\n"
"\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    \n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/dark_orange/img/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #3A3939;\n"
"    height: 8px;\n"
"    background: #201F1F;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"      stop: 0.0 silver, stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #3A3939;\n"
"    width: 8px;\n"
"    background: #201F1F;\n"
"    margin: 0 0px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 silver,\n"
"      stop: 0.2 #a8a8a8, stop: 1 #727272);\n"
"    border: 1px solid #3A3939;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: 0 -4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QAbstractSpinBox {\n"
"    padding-top: 2px;\n"
"    padding-bottom: 2px;\n"
"    border: 1px solid darkgray;\n"
"\n"
"    border-radius: 2px;\n"
"    min-width: 50px;\n"
"}\n"
"QToolBox  {\n"
"    padding: 5px;\n"
"    border: 1px transparent black;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    color: #eff0f1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 1px transparent #323232;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QToolBox::tab:selected { /* italicize selected tabs */\n"
"    font: italic;\n"
"    background-color: #323232;\n"
"    border-color: #D1DBCB;\n"
" }\n"
"QComboBox\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setLineWidth(3)
        self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1246, 920))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 40))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 251, 252);\n"
" background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgb(250, 0, 0), stop: 0.5 rgb(140, 0, 0));")
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 9, 0, 1, 7)
        self.line_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_16.sizePolicy().hasHeightForWidth())
        self.line_16.setSizePolicy(sizePolicy)
        self.line_16.setMaximumSize(QtCore.QSize(5, 16777215))
        self.line_16.setStyleSheet("border:none;")
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_3.addWidget(self.line_16, 8, 2, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_15.sizePolicy().hasHeightForWidth())
        self.line_15.setSizePolicy(sizePolicy)
        self.line_15.setMaximumSize(QtCore.QSize(15, 16777215))
        self.line_15.setStyleSheet("border:none;")
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_3.addWidget(self.line_15, 8, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 10, 1, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_13.sizePolicy().hasHeightForWidth())
        self.line_13.setSizePolicy(sizePolicy)
        self.line_13.setMaximumSize(QtCore.QSize(15, 16777215))
        self.line_13.setStyleSheet("border:none;")
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_3.addWidget(self.line_13, 8, 6, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: rgb(255, 251, 252);\n"
" background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgb(250, 0, 0), stop: 0.5 rgb(140, 0, 0));")
        self.label_1.setTextFormat(QtCore.Qt.RichText)
        self.label_1.setObjectName("label_1")
        self.gridLayout_3.addWidget(self.label_1, 0, 0, 1, 7)
        self.frame_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("background-color: rgb(255, 225, 230);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_13.setLineWidth(2)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.frame_13)
        self.scrollArea_6.setStyleSheet("border:none;")
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 278, 713))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.memory = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_6)
        self.memory.setObjectName("memory")
        self.gridLayout_10.addWidget(self.memory, 0, 0, 1, 1)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_12.addWidget(self.scrollArea_6)
        self.label_3 = QtWidgets.QLabel(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.gridLayout_3.addWidget(self.frame_13, 7, 4, 2, 2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMouseTracking(False)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 225, 230);")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stackedWidget.setLineWidth(2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_12 = QtWidgets.QScrollArea(self.page_1)
        self.scrollArea_12.setStyleSheet("QscrollArea{\n"
"border:none;\n"
"}")
        self.scrollArea_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_12.setWidgetResizable(True)
        self.scrollArea_12.setObjectName("scrollArea_12")
        self.scrollAreaWidgetContents_13 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_13.setGeometry(QtCore.QRect(0, 0, 816, 753))
        self.scrollAreaWidgetContents_13.setObjectName("scrollAreaWidgetContents_13")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_13)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.starting_adress = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.starting_adress.sizePolicy().hasHeightForWidth())
        self.starting_adress.setSizePolicy(sizePolicy)
        self.starting_adress.setMaximumSize(QtCore.QSize(300, 16777215))
        self.starting_adress.setStyleSheet("font: 75  9pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"    color: rgb(0, 0, 0);")
        self.starting_adress.setText("")
        self.starting_adress.setObjectName("starting_adress")
        self.gridLayout_6.addWidget(self.starting_adress, 9, 0, 1, 1)
        self.add_hole = QtWidgets.QPushButton(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_hole.sizePolicy().hasHeightForWidth())
        self.add_hole.setSizePolicy(sizePolicy)
        self.add_hole.setStyleSheet("QPushButton::hover\n"
"\n"
"{\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    font: 75  11pt bold \"Perpetua Titling MT\";\n"
"    color: rgb(170, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}")
        self.add_hole.setObjectName("add_hole")
        self.gridLayout_6.addWidget(self.add_hole, 12, 0, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_19.sizePolicy().hasHeightForWidth())
        self.line_19.setSizePolicy(sizePolicy)
        self.line_19.setMinimumSize(QtCore.QSize(0, 30))
        self.line_19.setStyleSheet("border:none;")
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_6.addWidget(self.line_19, 1, 0, 1, 1)
        self.hole_size = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hole_size.sizePolicy().hasHeightForWidth())
        self.hole_size.setSizePolicy(sizePolicy)
        self.hole_size.setMaximumSize(QtCore.QSize(300, 16777215))
        self.hole_size.setStyleSheet("font: 75  9pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"    color: rgb(0, 0, 0);")
        self.hole_size.setText("")
        self.hole_size.setObjectName("hole_size")
        self.gridLayout_6.addWidget(self.hole_size, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(400000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 251, 252);\n"
" background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgb(250, 0, 0), stop: 0.5 rgb(140, 0, 0));")
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 3)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet(" background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgb(208, 0, 0), stop: 0.5 rgb(170, 0, 0));")
        self.label_28.setTextFormat(QtCore.Qt.RichText)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 8, 0, 1, 1)
        self.next_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_2.sizePolicy().hasHeightForWidth())
        self.next_2.setSizePolicy(sizePolicy)
        self.next_2.setStyleSheet("QPushButton::hover\n"
"{\n"
"    border-color: rgb(255, 0, 0);\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton::pressed\n"
"\n"
"{        border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    font: 75  16pt bold \"Perpetua Titling MT\";\n"
"    border: 6px solid #555;\n"
"    border-radius: 27px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(138, 0, 0);\n"
"        border-color: rgb(138, 0, 0);\n"
"\n"
"\n"
"    padding:1px;\n"
"}\n"
"")
        self.next_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/circled-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_2.setIcon(icon1)
        self.next_2.setIconSize(QtCore.QSize(40, 40))
        self.next_2.setObjectName("next_2")
        self.gridLayout_6.addWidget(self.next_2, 18, 2, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setMinimumSize(QtCore.QSize(0, 30))
        self.line_5.setStyleSheet("border:none;")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_6.addWidget(self.line_5, 13, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_13)
        self.line_3.setStyleSheet("border:none;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_6.addWidget(self.line_3, 2, 2, 1, 1)
        self.delete_hole = QtWidgets.QPushButton(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_hole.sizePolicy().hasHeightForWidth())
        self.delete_hole.setSizePolicy(sizePolicy)
        self.delete_hole.setStyleSheet("QPushButton::hover\n"
"\n"
"{\n"
"    border-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    font: 75  11pt bold \"Perpetua Titling MT\";\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}")
        self.delete_hole.setObjectName("delete_hole")
        self.gridLayout_6.addWidget(self.delete_hole, 18, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setMinimumSize(QtCore.QSize(0, 30))
        self.line_4.setStyleSheet("border:none;")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_6.addWidget(self.line_4, 7, 0, 1, 1)
        self.hole_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hole_table.sizePolicy().hasHeightForWidth())
        self.hole_table.setSizePolicy(sizePolicy)
        self.hole_table.setMaximumSize(QtCore.QSize(4000000, 16777215))
        self.hole_table.setStyleSheet("QTableWidge::hover\n"
"\n"
"{\n"
"\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QTableWidget::item::hover\n"
"\n"
"{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QTableWidget::item::selected::none\n"
"\n"
"{\n"
"background-color: rgb(255, 225, 230);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QTableWidget{\n"
"        font: 75 12pt bold \"Perpetua Titling MT\";\n"
"\n"
"    color: rgb(0, 0, 0);\n"
"border:none;\n"
"\n"
"}\n"
"\n"
"")
        self.hole_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.hole_table.setObjectName("hole_table")
        self.hole_table.setColumnCount(2)
        self.hole_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.hole_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hole_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hole_table.setHorizontalHeaderItem(1, item)
        self.hole_table.horizontalHeader().setDefaultSectionSize(165)
        self.hole_table.horizontalHeader().setMinimumSectionSize(60)
        self.hole_table.verticalHeader().setDefaultSectionSize(37)
        self.gridLayout_6.addWidget(self.hole_table, 16, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 14, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet(" background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgb(208, 0, 0), stop: 0.5 rgb(170, 0, 0));")
        self.label_31.setTextFormat(QtCore.Qt.RichText)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 2, 0, 1, 1)
        self.memory_size = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memory_size.sizePolicy().hasHeightForWidth())
        self.memory_size.setSizePolicy(sizePolicy)
        self.memory_size.setMaximumSize(QtCore.QSize(300, 16777215))
        self.memory_size.setStyleSheet("\n"
"QLineEdit\n"
"{\n"
"font: 75  9pt \"MS Shell Dlg 2\";\n"
"\n"
"border-color: rgb(112, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.memory_size.setText("")
        self.memory_size.setObjectName("memory_size")
        self.gridLayout_6.addWidget(self.memory_size, 3, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setLineWidth(0)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_6.addWidget(self.line_7, 18, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setLineWidth(0)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_6.addWidget(self.line_6, 16, 1, 1, 2)
        self.scrollArea_12.setWidget(self.scrollAreaWidgetContents_13)
        self.gridLayout_4.addWidget(self.scrollArea_12, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_7.setStyleSheet("QscrollArea{\n"
"border:none;\n"
"}")
        self.scrollArea_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 816, 753))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_10.sizePolicy().hasHeightForWidth())
        self.line_10.setSizePolicy(sizePolicy)
        self.line_10.setMinimumSize(QtCore.QSize(300, 0))
        self.line_10.setLineWidth(0)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_11.addWidget(self.line_10, 22, 5, 1, 1)
        self.process_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_table.sizePolicy().hasHeightForWidth())
        self.process_table.setSizePolicy(sizePolicy)
        self.process_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.process_table.setStyleSheet("QTableWidge::hover\n"
"\n"
"{\n"
"\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QTableWidget::item::hover\n"
"\n"
"{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QTableWidget::item::selected::none\n"
"\n"
"{\n"
"background-color: rgb(255, 225, 230);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QTableWidget{\n"
"        font: 75 12pt bold \"Perpetua Titling MT\";\n"
"\n"
"    color: rgb(0, 0, 0);\n"
"border:none;\n"
"\n"
"}\n"
"\n"
"")
        self.process_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.process_table.setObjectName("process_table")
        self.process_table.setColumnCount(3)
        self.process_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.process_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_table.setHorizontalHeaderItem(2, item)
        self.process_table.verticalHeader().setVisible(False)
        self.gridLayout_11.addWidget(self.process_table, 16, 0, 1, 6)
        self.line_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_17.sizePolicy().hasHeightForWidth())
        self.line_17.setSizePolicy(sizePolicy)
        self.line_17.setMinimumSize(QtCore.QSize(0, 10))
        self.line_17.setStyleSheet("border:none;")
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_11.addWidget(self.line_17, 6, 0, 1, 1)
        self.process_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process_name.sizePolicy().hasHeightForWidth())
        self.process_name.setSizePolicy(sizePolicy)
        self.process_name.setMaximumSize(QtCore.QSize(300, 16777215))
        self.process_name.setStyleSheet("\n"
"QLineEdit\n"
"{\n"
"font: 75  9pt \"MS Shell Dlg 2\";\n"
"\n"
"border-color: rgb(112, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.process_name.setText("")
        self.process_name.setObjectName("process_name")
        self.gridLayout_11.addWidget(self.process_name, 8, 0, 1, 1)
        self.ok = QtWidgets.QPushButton(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        self.ok.setStyleSheet("QPushButton::hover\n"
"\n"
"{\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    font: 75  11pt bold \"Perpetua Titling MT\";\n"
"    color: rgb(170, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}")
        self.ok.setObjectName("ok")
        self.gridLayout_11.addWidget(self.ok, 10, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet(" background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgb(208, 0, 0), stop: 0.5 rgb(170, 0, 0));")
        self.label_32.setTextFormat(QtCore.Qt.RichText)
        self.label_32.setObjectName("label_32")
        self.gridLayout_11.addWidget(self.label_32, 7, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 15, 0, 1, 1)
        self.delete_process = QtWidgets.QPushButton(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_process.sizePolicy().hasHeightForWidth())
        self.delete_process.setSizePolicy(sizePolicy)
        self.delete_process.setStyleSheet("QPushButton::hover\n"
"\n"
"{\n"
"    border-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    font: 75  11pt bold \"Perpetua Titling MT\";\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}")
        self.delete_process.setObjectName("delete_process")
        self.gridLayout_11.addWidget(self.delete_process, 21, 0, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_20.sizePolicy().hasHeightForWidth())
        self.line_20.setSizePolicy(sizePolicy)
        self.line_20.setMinimumSize(QtCore.QSize(0, 10))
        self.line_20.setStyleSheet("border:none;")
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_11.addWidget(self.line_20, 11, 0, 1, 1)
        self.segments_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segments_table.sizePolicy().hasHeightForWidth())
        self.segments_table.setSizePolicy(sizePolicy)
        self.segments_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.segments_table.setBaseSize(QtCore.QSize(500, 0))
        self.segments_table.setStyleSheet("QTableWidge::hover\n"
"\n"
"{\n"
"\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QTableWidget::item::hover\n"
"\n"
"{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QTableWidget::item::selected::none\n"
"\n"
"{\n"
"background-color: rgb(255, 225, 230);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QTableWidget{\n"
"        font: 75 12pt bold \"Perpetua Titling MT\";\n"
"\n"
"    color: rgb(0, 0, 0);\n"
"border:none;\n"
"\n"
"}\n"
"\n"
"")
        self.segments_table.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.segments_table.setDragEnabled(True)
        self.segments_table.setObjectName("segments_table")
        self.segments_table.setColumnCount(2)
        self.segments_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.segments_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.segments_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.segments_table.setHorizontalHeaderItem(1, item)
        self.segments_table.verticalHeader().setVisible(False)
        self.segments_table.verticalHeader().setCascadingSectionResizes(False)
        self.segments_table.verticalHeader().setDefaultSectionSize(37)
        self.segments_table.verticalHeader().setHighlightSections(True)
        self.gridLayout_11.addWidget(self.segments_table, 13, 0, 1, 3)
        self.worst_fit = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.worst_fit.sizePolicy().hasHeightForWidth())
        self.worst_fit.setSizePolicy(sizePolicy)
        self.worst_fit.setMaximumSize(QtCore.QSize(16777215, 16))
        self.worst_fit.setStyleSheet("color: rgb(131, 0, 0);\n"
"    font: 75  11pt bold \"Perpetua Titling MT\";\n"
"\n"
"")
        self.worst_fit.setChecked(False)
        self.worst_fit.setObjectName("worst_fit")
        self.gridLayout_11.addWidget(self.worst_fit, 5, 0, 1, 1)
        self.back = QtWidgets.QPushButton(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        self.back.setStyleSheet("QPushButton::hover\n"
"{\n"
"    border-color: rgb(255, 0, 0);\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton::pressed\n"
"\n"
"{        border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    font: 75  16pt bold \"Perpetua Titling MT\";\n"
"    border: 6px solid #555;\n"
"    border-radius: 27px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(138, 0, 0);\n"
"        border-color: rgb(138, 0, 0);\n"
"\n"
"\n"
"    padding:1px;\n"
"}\n"
"")
        self.back.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/circled-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon2)
        self.back.setIconSize(QtCore.QSize(40, 40))
        self.back.setObjectName("back")
        self.gridLayout_11.addWidget(self.back, 21, 6, 5, 1)
        self.best_fit = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.best_fit.sizePolicy().hasHeightForWidth())
        self.best_fit.setSizePolicy(sizePolicy)
        self.best_fit.setMaximumSize(QtCore.QSize(16777215, 16))
        self.best_fit.setStyleSheet("color: rgb(131, 0, 0);\n"
"    font: 75  11pt bold \"Perpetua Titling MT\";\n"
"\n"
"")
        self.best_fit.setChecked(False)
        self.best_fit.setObjectName("best_fit")
        self.gridLayout_11.addWidget(self.best_fit, 4, 0, 1, 1)
        self.first_fit = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_fit.sizePolicy().hasHeightForWidth())
        self.first_fit.setSizePolicy(sizePolicy)
        self.first_fit.setMaximumSize(QtCore.QSize(16777215, 16))
        self.first_fit.setStyleSheet("color: rgb(131, 0, 0);\n"
"    font: 75  11pt bold \"Perpetua Titling MT\";\n"
"\n"
"")
        self.first_fit.setChecked(False)
        self.first_fit.setObjectName("first_fit")
        self.gridLayout_11.addWidget(self.first_fit, 3, 0, 1, 5)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(340, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 251, 252);\n"
" background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0  rgb(250, 0, 0), stop: 0.5 rgb(140, 0, 0));")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.gridLayout_11.addWidget(self.label, 2, 0, 1, 1)
        self.no_of_segments = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.no_of_segments.sizePolicy().hasHeightForWidth())
        self.no_of_segments.setSizePolicy(sizePolicy)
        self.no_of_segments.setMaximumSize(QtCore.QSize(300, 16777215))
        self.no_of_segments.setStyleSheet("\n"
"QLineEdit\n"
"{\n"
"font: 75  9pt \"MS Shell Dlg 2\";\n"
"\n"
"border-color: rgb(112, 0, 0);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.no_of_segments.setText("")
        self.no_of_segments.setObjectName("no_of_segments")
        self.gridLayout_11.addWidget(self.no_of_segments, 9, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 12, 0, 1, 1)
        self.compaction = QtWidgets.QPushButton(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compaction.sizePolicy().hasHeightForWidth())
        self.compaction.setSizePolicy(sizePolicy)
        self.compaction.setStyleSheet("QPushButton::hover\n"
"\n"
"{\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    font: 75  11pt bold \"Perpetua Titling MT\";\n"
"    color: rgb(170, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}")
        self.compaction.setObjectName("compaction")
        self.gridLayout_11.addWidget(self.compaction, 22, 0, 1, 1)
        self.add_process = QtWidgets.QPushButton(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_process.sizePolicy().hasHeightForWidth())
        self.add_process.setSizePolicy(sizePolicy)
        self.add_process.setStyleSheet("QPushButton::hover\n"
"\n"
"{\n"
"    border-color: rgb(255, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    font: 75  11pt bold \"Perpetua Titling MT\";\n"
"    color: rgb(170, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}")
        self.add_process.setObjectName("add_process")
        self.gridLayout_11.addWidget(self.add_process, 14, 0, 1, 1)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_13.addWidget(self.scrollArea_7)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_3.addWidget(self.stackedWidget, 8, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Memory Allocator"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Memory Allocator Using Segmentation</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#730000;\">Memory</span></p></body></html>"))
        self.starting_adress.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#818181;\">Hole starting address</span></p></body></html>"))
        self.starting_adress.setPlaceholderText(_translate("MainWindow", "Enter the hole starting address"))
        self.add_hole.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add Hole</p></body></html>"))
        self.add_hole.setText(_translate("MainWindow", "Add Hole"))
        self.hole_size.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#818181;\">Hole size</span></p></body></html>"))
        self.hole_size.setPlaceholderText(_translate("MainWindow", "Enter the hole size"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Memory Current State</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#ecdbd8;\">Hole Information</span></p></body></html>"))
        self.next_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Next</p></body></html>"))
        self.delete_hole.setToolTip(_translate("MainWindow", "<html><head/><body><p>De-allocate Selected Hole</p></body></html>"))
        self.delete_hole.setText(_translate("MainWindow", "De-allocate Selected Hole"))
        self.hole_table.setToolTip(_translate("MainWindow", "<html><head/><body><p>Hole starting adress</p><p>Hole size</p></body></html>"))
        item = self.hole_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hole Starting Address"))
        item = self.hole_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hole Size"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#910000;\">Please fill in the hole starting adress and size.  </span></p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#ecdbd8;\">Memory Size</span></p></body></html>"))
        self.memory_size.setToolTip(_translate("MainWindow", "<html><head/><body><p>Memory size</p></body></html>"))
        self.memory_size.setPlaceholderText(_translate("MainWindow", "Enter the memory size"))
        self.process_table.setToolTip(_translate("MainWindow", "<html><head/><body><p>Process name</p><p>No_Of Segments</p><p>Segments information</p></body></html>"))
        item = self.process_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Process Name"))
        item = self.process_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "No_Of Segments"))
        item = self.process_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Segments Info."))
        self.process_name.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#545454;\">Total process name</span></p></body></html>"))
        self.process_name.setPlaceholderText(_translate("MainWindow", "Enter the total process name"))
        self.ok.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ok</p></body></html>"))
        self.ok.setText(_translate("MainWindow", "Ok"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#ecdbd8;\">Process Information:  </span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#910000;\">Process table: </span></p></body></html>"))
        self.delete_process.setToolTip(_translate("MainWindow", "<html><head/><body><p>De-allocate Selected Process</p></body></html>"))
        self.delete_process.setText(_translate("MainWindow", "De-allocate Selected Process"))
        self.segments_table.setToolTip(_translate("MainWindow", "<html><head/><body><p>Segment name</p><p>Segment size</p></body></html>"))
        item = self.segments_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Segment Name"))
        item = self.segments_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Segment Size"))
        self.worst_fit.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#585858;\">Worst Fit</span></p></body></html>"))
        self.worst_fit.setText(_translate("MainWindow", "Worst Fit"))
        self.back.setToolTip(_translate("MainWindow", "<html><head/><body><p>Back</p></body></html>"))
        self.best_fit.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#585858;\">Best Fit</span></p></body></html>"))
        self.best_fit.setText(_translate("MainWindow", "Best Fit"))
        self.first_fit.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#585858;\">First Fit</span></p></body></html>"))
        self.first_fit.setText(_translate("MainWindow", "First Fit"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Choose Memory Allocation Algorithm:</span></p></body></html>"))
        self.no_of_segments.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4f4f4f;\">Number of segments</span></p></body></html>"))
        self.no_of_segments.setPlaceholderText(_translate("MainWindow", "Enter the number of segments"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#910000;\">Please fill in the segments names and sizes.</span></p></body></html>"))
        self.compaction.setToolTip(_translate("MainWindow", "<html><head/><body><p>ِِِِApply Compaction</p></body></html>"))
        self.compaction.setText(_translate("MainWindow", "ِِِِApply Compaction"))
        self.add_process.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add Process</p></body></html>"))
        self.add_process.setText(_translate("MainWindow", "Add Process"))
import memory_allocator_rc
